### ISSUE TITLE
batch insert questions

### ISSUE THREAD

**Issue by mysunnyshine** [scylladb/gocqlx#123] opened 2019-11-08 07:21 UTC
I write the Batch Function for testing batch. 
However,  the values are not expected. I expect the value [0 1 2 1 2 3], but [1 2 3 1 2 3]
![image](https://user-images.githubusercontent.com/24480430/68457412-3395c200-023b-11ea-8eea-447c969e767a.png)
![image](https://user-images.githubusercontent.com/24480430/68457470-57f19e80-023b-11ea-8fa1-db4758f3729d.png)

**Comment by dahankzter** [comment] 2019-11-08 08:26
Can you attach a runnable program exhibiting this?

**Comment by mysunnyshine** [comment] 2019-11-08 09:23
> exhibiting

`func BenchmarkBatchSet(b *testing.B) {
	var batchCols = []string{"id", "first_name", "last_name"}
	session := CreateSession(b)
	defer session.Close()
	msetNum := 2
	if err := ExecStmt(session, benchPersonSchema); err != nil {
		b.Fatal(err)
	}
	bt := qb.Batch();
	for i := 0; i < msetNum; i++ {
		bt.Add(qb.Insert("gocqlx_test.bench_person").Columns(batchCols...))
	}
	stmt, names := bt.ToCql()
	q := gocqlx.Query(session.Query(stmt), names)
	for i := 0; i < msetNum; i++ {
		q.BindStruct(&benchPerson{
			ID: i,
			FirstName: strconv.Itoa(i + 1),
			LastName: strconv.Itoa(i + 2),
		})
	}
	fmt.Println("query = ", q.Query)
	defer q.Release()
	b.ResetTimer()
	if e1 := q.Exec(); e1 != nil {
		b.Fatal(e1)
	}
}`

**Comment by mysunnyshine** [comment] 2019-11-08 09:24
func BenchmarkBatchSet(b *testing.B) {
	var batchCols = []string{"id", "first_name", "last_name"}
	session := CreateSession(b)
	defer session.Close()
	msetNum := 2
	if err := ExecStmt(session, benchPersonSchema); err != nil {
		b.Fatal(err)
	}
	bt := qb.Batch();
	for i := 0; i < msetNum; i++ {
		bt.Add(qb.Insert("gocqlx_test.bench_person").Columns(batchCols...))
	}
	stmt, names := bt.ToCql()
	q := gocqlx.Query(session.Query(stmt), names)
	for i := 0; i < msetNum; i++ {
		q.BindStruct(&benchPerson{
			ID: i,
			FirstName: strconv.Itoa(i + 1),
			LastName: strconv.Itoa(i + 2),
		})
	}
	fmt.Println("query = ", q.Query)
	defer q.Release()
	b.ResetTimer()
	if e1 := q.Exec(); e1 != nil {
		b.Fatal(e1)
	}
}

**Comment by dahankzter** [comment] 2019-11-08 10:20
So let me see if I get this straight. You want to execute the same query several times in a batch with different values for each query in the batch.
Correct?

Since Batch is effectively treats many queries masked as a single query what bind does is that it applies the same bound values for each query in the batch. Every `Bind` rebinds the values to the new values and applies them to the entire batch.
This behavior is consistent with how `Bind` works for non-batch queries.

I guess arguments could be made for changing the behavior but I have no idea how complicated an implementation would be and changing the API is probably not a good idea so some other method would be needed in that case.

**Comment by mysunnyshine** [comment] 2019-11-08 12:49
> So let me see if I get this straight. You want to execute the same query several times in a batch with different values for each query in the batch.
> Correct?
> 
> Since Batch is effectively treats many queries masked as a single query what bind does is that it applies the same bound values for each query in the batch. Every `Bind` rebinds the values to the new values and applies them to the entire batch.
> This behavior is consistent with how `Bind` works for non-batch queries.
> 
> I guess arguments could be made for changing the behavior but I have no idea how complicated an implementation would be and changing the API is probably not a good idea so some other method would be needed in that case.

 Simply, I just want to test the batch command like mget or mset in redis. 
Could you please give me some example?

**Comment by mysunnyshine** [comment] 2019-11-09 03:08
solved it by this:
![image](https://user-images.githubusercontent.com/24480430/68521983-4cf14980-02e1-11ea-8ef6-c36f9af4c51e.png)

**Comment by mmatczuk** [comment] 2019-11-09 03:32
Duplicate of #110

**Closed by mmatczuk** 2019-11-09 03:32 UTC
